[build]
  functions = "backend/functions"
  publish = "frontend/dist"
  command = "npm run build"

[dev]
  port = 8888
  functions = "backend/functions"
  framework = "#auto"
  command = "npm run client"

[functions]
  node_bundler = "esbuild"
  esbuild_options = { format = "esm" }

# Adding environment variables for the development environment
[dev.environment]
  REDIS_URL = "redis://localhost:6379"
  PORT = "8000"