[build]
  command = "yarn netlify:build"
  publish = "frontend/dist"
  functions = "backend/functions"

[dev]
  port = 8888
  functions = "backend/functions"
  framework = "#auto"
  command = "yarn client"

[functions]
  node_bundler = "esbuild"
  esbuild_options = { format = "esm" }

[dev.environment]
  REDIS_URL = "redis://localhost:6379"

[build.environment]
  NODE_VERSION = "18"
  YARN_VERSION = "1.22.22"
  YARN_FLAGS = "--network-timeout 600000"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/api/:splat"
  status = 200

