[build]
  command = "npm install && npm run netlify:build"
  publish = "frontend/dist"
  functions = "backend/functions"

[dev]
  port = 8888
  functions = "backend/functions"
  framework = "#auto"
  command = "npm run client"

[functions]
  node_bundler = "esbuild"
  included_files = ["backend/**/*"]
  
[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

