[build]
  functions = "backend/functions"
  publish = "frontend/dist"
  command = "npm run build"

[dev]
  port = 8888
  functions = "backend/functions"
  framework = "vue"
  targetPort = 8080
  command = "npm run client"

[functions]
  node_bundler = "esbuild"

# Adding environment variables for the development environment
[dev.environment]
  REDIS_URL = "redis://localhost:6379"
  PORT = "8000"


